apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: python:3.9
      script: |
        #!/bin/sh
        echo "Cleaning up temporary files..."
        rm -rf /tmp/* || true
        echo "Cleanup completed successfully."

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: test
      image: python:3.9
      script: |
        #!/bin/sh
        pip install --quiet nose
        echo "Running unit tests..."
        nosetests -v .github/workflows/test_app.py
